export const terms_db = [
  {
    fr: "Conditions d'Utilisation",
    pt: "Termos de Uso",
    en: "Terms of Use",
  },
  {
    fr: [
      "title - Subtitle 1",
      "<p> - FR - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 2",
      "<p> - FR - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 3",
      "subttl - Subtitle",
      "<p> - FR - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 4",
      "<p> - FR - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 5",
      "<p> - FR - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
    ],
    pt: [
      "title - Subtitle 1",
      "<p> - PT - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 2",
      "<p> - PT - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 3",
      "subttl - Subtitle",
      "<p> - PT - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 4",
      "<p> - PT - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 5",
      "<p> - PT - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
    ],
    en: [
      "title - Subtitle 1",
      "<p> - EN - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 2",
      "<p> - EN - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 3",
      "subttl - Subtitle",
      "<p> - EN - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 4",
      "<p> - EN - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
      "title - Subtitle 5",
      "<p> - EN - Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus illo, corrupti commodi molestiae recusandae pariatur quas, excepturi doloremque aliquid iusto eligendi? Nulla officia enim itaque harum tenetur quaerat blanditiis natus.",
    ],
  },
];
